/**
 * Emit SQL that seeds the three demo scenarios into a Postgres-backed deployment.
 *
 * `lib/db/seed.ts` is the single source of truth for demo content; `MemoryRepository`
 * installs it directly as JS objects on every cold start, which is why demo mode "just
 * works" locally with zero configuration. Supabase has no equivalent bootstrap step — a
 * fresh `pact` schema starts empty, so `DEMO_VIEWER` sees nothing until this is run once.
 *
 * Two things `demoPacts()`'s output cannot go into Postgres as-is:
 *
 *  - Every id in there ("demo-website", "demo-website-m1", ...) is a human-readable
 *    string, but every id column in the schema is `uuid`. Real ids are generated here
 *    and threaded through every foreign key by hand — nothing relies on the literal
 *    "demo-*" strings surviving into the database. The app never depends on them either:
 *    the dashboard reads real ids back from Postgres and links to `/p/<uuid>` itself.
 *  - The placeholder signatures ("demo-signature-demo-website-client") are for a UI that
 *    only checks whether a signature is present, but the schema's check constraints
 *    enforce the real shape (128 hex chars for a signature, 64 for a public key) even for
 *    seed data. Replaced with generated hex of the right length below.
 *
 * Usage: node scripts/seed-supabase.ts > seed.sql
 * Then run seed.sql against the target project (e.g. via the Supabase MCP's execute_sql,
 * or `psql`). Every statement is `on conflict do nothing` / keyed off fixed UUIDs derived
 * from the demo ids, so re-running is harmless.
 */
import { randomBytes } from 'node:crypto'
import { demoPacts, DEMO_VIEWER } from '../lib/db/seed.ts'
import { normalizeAddress } from '../lib/nimiq/address.ts'

function hex(bytes: number): string {
  return randomBytes(bytes).toString('hex')
}

// Deterministic UUIDs (v4 shape, not v4-random) derived from the original demo string id,
// so re-running this script against the same seed data produces the same rows rather than
// duplicating them.
function uuidFrom(key: string): string {
  const digest = randomBytesFromString(key)
  return [digest.slice(0, 8), digest.slice(8, 12), '4' + digest.slice(13, 16), 'a' + digest.slice(17, 20), digest.slice(20, 32)].join('-')
}

function randomBytesFromString(input: string): string {
  // Not cryptographic — just needs to be stable per input string. FNV-1a expanded to 32 hex chars.
  let h1 = 0x811c9dc5
  for (let i = 0; i < input.length; i++) {
    h1 ^= input.charCodeAt(i)
    h1 = Math.imul(h1, 0x01000193)
  }
  let h2 = 0x811c9dc5 ^ 0x9e3779b9
  for (let i = input.length - 1; i >= 0; i--) {
    h2 ^= input.charCodeAt(i)
    h2 = Math.imul(h2, 0x01000193)
  }
  const a = (h1 >>> 0).toString(16).padStart(8, '0')
  const b = (h2 >>> 0).toString(16).padStart(8, '0')
  return (a + b + a + b).slice(0, 32)
}

function sqlStr(value: string | null): string {
  if (value === null) return 'null'
  return `'${value.replace(/'/g, "''")}'`
}

function sqlArr(values: string[]): string {
  if (values.length === 0) return "'{}'"
  return `ARRAY[${values.map((v) => sqlStr(v)).join(', ')}]::text[]`
}

function sqlJsonb(value: Record<string, unknown>): string {
  return `${sqlStr(JSON.stringify(value))}::jsonb`
}

const lines: string[] = []
lines.push('-- Generated by scripts/seed-supabase.ts. Safe to re-run.', 'set search_path = pact, public;', '')

const userAddresses = new Set<string>()
const userNames = new Map<string, string>()

for (const pact of demoPacts()) {
  const pactId = uuidFrom(pact.id)
  const milestoneIdMap = new Map<string, string>()

  for (const p of pact.participants) {
    if (!p.address) continue
    const addr = normalizeAddress(p.address)
    userAddresses.add(addr)
    if (p.displayName) userNames.set(addr, p.displayName)
  }

  // --- users + profiles ---------------------------------------------------------------
  for (const addr of [...userAddresses]) {
    lines.push(
      `insert into pact.users (address) values (${sqlStr(addr)}) on conflict (address) do nothing;`,
    )
    const name = userNames.get(addr)
    if (name) {
      lines.push(
        `insert into pact.profiles (address, display_name) values (${sqlStr(addr)}, ${sqlStr(name)}) ` +
          `on conflict (address) do update set display_name = excluded.display_name;`,
      )
    }
  }
  userAddresses.clear()

  // --- pacts ----------------------------------------------------------------------------
  lines.push(
    `insert into pact.pacts (id, short_id, title, deliverable, created_by, status, currency, chain, total_amount_minor, deadline, payment_condition, special_terms, terms_digest, created_at, updated_at) values (` +
      [
        sqlStr(pactId),
        sqlStr(pact.shortId),
        sqlStr(pact.title),
        sqlStr(pact.deliverable),
        sqlStr(normalizeAddress(pact.createdBy)),
        sqlStr(pact.status),
        sqlStr(pact.currency),
        pact.chain ? sqlStr(pact.chain) : 'null',
        sqlStr(pact.totalAmountMinor),
        pact.deadline ? sqlStr(pact.deadline) : 'null',
        sqlStr(pact.paymentCondition),
        sqlArr(pact.specialTerms),
        sqlStr(pact.termsDigest),
        sqlStr(pact.createdAt),
        sqlStr(pact.updatedAt),
      ].join(', ') +
      `) on conflict (id) do update set status = excluded.status, terms_digest = excluded.terms_digest, updated_at = excluded.updated_at;`,
  )

  // --- participants -----------------------------------------------------------------
  for (const p of pact.participants) {
    const signature = p.sealSignature ? hex(64) : null // 64 bytes -> 128 hex chars
    const publicKey = p.sealPublicKey ? hex(32) : null // 32 bytes -> 64 hex chars
    lines.push(
      `insert into pact.pact_participants (id, pact_id, role, address, display_name, evm_address, seal_signature, seal_public_key, sealed_at, joined_at) values (` +
        [
          sqlStr(uuidFrom(p.id)),
          sqlStr(pactId),
          sqlStr(p.role),
          p.address ? sqlStr(normalizeAddress(p.address)) : 'null',
          sqlStr(p.displayName),
          p.evmAddress ? sqlStr(p.evmAddress) : 'null',
          signature ? sqlStr(signature) : 'null',
          publicKey ? sqlStr(publicKey) : 'null',
          p.sealedAt ? sqlStr(p.sealedAt) : 'null',
          p.joinedAt ? sqlStr(p.joinedAt) : 'null',
        ].join(', ') +
        `) on conflict (pact_id, role) do update set seal_signature = excluded.seal_signature, seal_public_key = excluded.seal_public_key, sealed_at = excluded.sealed_at;`,
    )
  }

  // --- milestones -----------------------------------------------------------------------
  for (const m of pact.milestones) {
    const freshId = uuidFrom(m.id)
    milestoneIdMap.set(m.id, freshId)
    lines.push(
      `insert into pact.milestones (id, pact_id, position, title, description, amount_minor, percent, due_date, status, created_at, updated_at) values (` +
        [
          sqlStr(freshId),
          sqlStr(pactId),
          m.position,
          sqlStr(m.title),
          sqlStr(m.description),
          sqlStr(m.amountMinor),
          m.percent,
          m.dueDate ? sqlStr(m.dueDate) : 'null',
          sqlStr(m.status),
          sqlStr(m.createdAt),
          sqlStr(m.updatedAt),
        ].join(', ') +
        `) on conflict (pact_id, position) do update set status = excluded.status;`,
    )
  }

  // --- payments ---------------------------------------------------------------------
  for (const pay of pact.payments) {
    lines.push(
      `insert into pact.payments (id, pact_id, milestone_id, from_address, to_address, amount_minor, currency, chain, status, tx_reference, memo, failure_reason, idempotency_key, created_at, updated_at) values (` +
        [
          sqlStr(uuidFrom(pay.id)),
          sqlStr(pactId),
          pay.milestoneId ? sqlStr(milestoneIdMap.get(pay.milestoneId)!) : 'null',
          sqlStr(normalizeAddress(pay.fromAddress)),
          sqlStr(normalizeAddress(pay.toAddress)),
          sqlStr(pay.amountMinor),
          sqlStr(pay.currency),
          pay.chain ? sqlStr(pay.chain) : 'null',
          sqlStr(pay.status),
          pay.txReference ? sqlStr(pay.txReference) : 'null',
          pay.memo ? sqlStr(pay.memo) : 'null',
          pay.failureReason ? sqlStr(pay.failureReason) : 'null',
          sqlStr(pay.idempotencyKey),
          sqlStr(pay.createdAt),
          sqlStr(pay.updatedAt),
        ].join(', ') +
        `) on conflict (idempotency_key) do nothing;`,
    )
  }

  // --- deliverables -------------------------------------------------------------------
  for (const d of pact.deliverables) {
    lines.push(
      `insert into pact.deliverables (id, pact_id, milestone_id, submitted_by, note, link, status, review_note, created_at, updated_at) values (` +
        [
          sqlStr(uuidFrom(d.id)),
          sqlStr(pactId),
          d.milestoneId ? sqlStr(milestoneIdMap.get(d.milestoneId)!) : 'null',
          sqlStr(normalizeAddress(d.submittedBy)),
          sqlStr(d.note),
          d.link ? sqlStr(d.link) : 'null',
          sqlStr(d.status),
          d.reviewNote ? sqlStr(d.reviewNote) : 'null',
          sqlStr(d.createdAt),
          sqlStr(d.updatedAt),
        ].join(', ') +
        `) on conflict (id) do nothing;`,
    )
  }

  // --- negotiations + changes ---------------------------------------------------------
  for (const n of pact.negotiations) {
    const negotiationId = uuidFrom(n.id)
    lines.push(
      `insert into pact.negotiations (id, pact_id, proposed_by, message, status, created_at, resolved_at) values (` +
        [
          sqlStr(negotiationId),
          sqlStr(pactId),
          sqlStr(normalizeAddress(n.proposedBy)),
          sqlStr(n.message),
          sqlStr(n.status),
          sqlStr(n.createdAt),
          n.resolvedAt ? sqlStr(n.resolvedAt) : 'null',
        ].join(', ') +
        `) on conflict (id) do nothing;`,
    )
    for (const c of n.changes) {
      lines.push(
        `insert into pact.negotiation_changes (id, negotiation_id, field, label, original_value, proposed_value) values (` +
          [sqlStr(uuidFrom(c.id)), sqlStr(negotiationId), sqlStr(c.field), sqlStr(c.label), sqlStr(c.originalValue), sqlStr(c.proposedValue)].join(', ') +
          `) on conflict (id) do nothing;`,
      )
    }
  }

  // --- activities ---------------------------------------------------------------------
  for (const a of pact.activities) {
    lines.push(
      `insert into pact.activities (id, pact_id, kind, actor_address, actor_name, summary, meta, created_at) values (` +
        [
          sqlStr(uuidFrom(a.id)),
          sqlStr(pactId),
          sqlStr(a.kind),
          a.actorAddress ? sqlStr(normalizeAddress(a.actorAddress)) : 'null',
          sqlStr(a.actorName),
          sqlStr(a.summary),
          sqlJsonb((a.meta ?? {}) as Record<string, unknown>),
          sqlStr(a.createdAt),
        ].join(', ') +
        `) on conflict (id) do nothing;`,
    )
  }

  lines.push('')
}

lines.push(`-- DEMO_VIEWER: ${DEMO_VIEWER.address} (${DEMO_VIEWER.name}) — already among the participants above.`)

console.log(lines.join('\n'))
